
import React, { useState } from 'react';
import { AnalysisData, ContentSection } from '../types';
import ScoreOverview from './ScoreOverview';
import OnPageTab from './tabs/OnPageTab';
import KeywordsTab from './tabs/KeywordsTab';
import TechnicalTab from './tabs/TechnicalTab';
import AIInsightsTab from './tabs/AIInsightsTab';
import RecommendationsTab from './tabs/RecommendationsTab';
import ContentStructureTab from './tabs/ContentStructureTab';
import './ResultsSection.css';

interface ResultsSectionProps {
  data: AnalysisData;
  keywordSuggestions: string[];
  onSectionRewrite: (section: ContentSection) => void;
  onReset: () => void;
  aiModel: string;
  onOpenDeploy: () => void;
}

type TabType = 'structure' | 'onpage' | 'keywords' | 'technical' | 'aiinsights' | 'recommendations';

const ResultsSection: React.FC<ResultsSectionProps> = ({ 
  data, 
  keywordSuggestions, 
  onSectionRewrite,
  onReset,
  aiModel,
  onOpenDeploy
}) => {
  const [activeTab, setActiveTab] = useState<TabType>('structure');

  const tabs: { id: TabType; label: string; icon: string; isNew?: boolean }[] = [
    { id: 'structure', label: 'Content Structure', icon: 'fa-sitemap', isNew: true },
    { id: 'onpage', label: 'On-Page SEO', icon: 'fa-file-alt' },
    { id: 'keywords', label: 'Keywords', icon: 'fa-key' },
    { id: 'technical', label: 'Technical', icon: 'fa-cogs' },
    { id: 'aiinsights', label: 'AI Insights', icon: 'fa-brain' },
    { id: 'recommendations', label: 'Recommendations', icon: 'fa-lightbulb' }
  ];

  const downloadReport = (format: 'json' | 'txt') => {
    const filename = `seo-report-${data.domain}-${new Date().toISOString().split('T')[0]}`;
    
    if (format === 'json') {
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.json`;
      a.click();
      URL.revokeObjectURL(url);
    } else {
      const report = generateTextReport(data);
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const generateTextReport = (data: AnalysisData): string => {
    const ai = data.aiAnalysis;
    return `
SEO ANALYSIS REPORT (AI-Powered)
================================
URL: ${data.url}
Date: ${new Date().toLocaleDateString()}

OVERALL SCORE: ${ai.overallScore}/100

SCORE BREAKDOWN
---------------
On-Page SEO: ${ai.scores?.onPage?.score || 0}/25
Keywords & Content: ${ai.scores?.keywords?.score || 0}/25
Technical SEO: ${ai.scores?.technical?.score || 0}/30
UX & Mobile: ${ai.scores?.uxMobile?.score || 0}/20

SUMMARY
-------
${ai.summary || 'N/A'}

RECOMMENDATIONS
---------------
${(ai.recommendations || []).map((r, i) => `${i + 1}. [${r.priority.toUpperCase()}] ${r.title}\n   ${r.description}`).join('\n\n')}

---
Generated by SEO Analyzer Pro
    `.trim();
  };

  return (
    <section className="results-section fade-in">
      {/* AI Analysis Banner */}
      <div className="analysis-banner">
        <div className="banner-content">
          <div className="banner-icon">
            <i className="fas fa-robot"></i>
          </div>
          <div className="banner-text">
            <h3>AI-Powered Analysis Complete</h3>
            <p>Scored against 55 SEO criteria using <span className="model-name">{aiModel.split('/')[1] || aiModel}</span></p>
          </div>
        </div>
        <div className="banner-time">
          <i className="fas fa-clock"></i>
          <span>Analyzed: {new Date(data.analyzedAt).toLocaleString()}</span>
        </div>
      </div>

      <ScoreOverview data={data} />

      {/* Tabs Navigation */}
      <div className="tabs-container">
        <div className="tabs-nav">
          {tabs.map(tab => (
            <button
              key={tab.id}
              className={`tab-btn ${activeTab === tab.id ? 'tab-active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              <i className={`fas ${tab.icon}`}></i>
              {tab.label}
              {tab.isNew && <span className="tab-new-badge">NEW</span>}
            </button>
          ))}
        </div>

        <div className="tab-content">
          {activeTab === 'structure' && (
            <ContentStructureTab 
              data={data} 
              onSectionRewrite={onSectionRewrite}
              keywordSuggestions={keywordSuggestions}
            />
          )}
          {activeTab === 'onpage' && <OnPageTab data={data} />}
          {activeTab === 'keywords' && <KeywordsTab data={data} keywordSuggestions={keywordSuggestions} />}
          {activeTab === 'technical' && <TechnicalTab data={data} />}
          {activeTab === 'aiinsights' && <AIInsightsTab data={data} />}
          {activeTab === 'recommendations' && <RecommendationsTab data={data} />}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="action-buttons">
        <button onClick={onOpenDeploy} className="action-btn btn-vercel">
          <svg height="16" viewBox="0 0 75 65" fill="currentColor" style={{ marginRight: '6px' }}>
            <path d="M37.59.25l36.95 64H.64l36.95-64z"></path>
          </svg>
          Deploy to Vercel
        </button>
        <button onClick={() => downloadReport('txt')} className="action-btn btn-red">
          <i className="fas fa-file-pdf"></i> Download Report
        </button>
        <button onClick={() => downloadReport('json')} className="action-btn btn-blue">
          <i className="fas fa-code"></i> Export JSON
        </button>
        <button onClick={onReset} className="action-btn btn-gray">
          <i className="fas fa-redo"></i> New Analysis
        </button>
      </div>
    </section>
  );
};

export default ResultsSection;
